### ISSUE TITLE
难度练习切换别的网页后回来会自动刷新

### ISSUE THREAD

**Issue by Bearx666** [huxulm/lc-rating#15]
请问最近是有更新吗，我最近在难度练习那边发现做完题回来会自动刷新网页，但是之前都没有这个问题

**Comment by huxulm** [comment]
前面一版有点小bug，已经修复。

**Comment by Bearx666** [comment]
> 前面一版有点小bug，已经修复。

请问对浏览器有要求限制吗，我在mbp上用edge和safari还是有刷新的问题
