### ISSUE TITLE
为什么切换标签页要重新加载呢？

### ISSUE THREAD

**Issue by shenxiang11** [huxulm/lc-rating#16]
分页页码回到第一页

**Comment by huxulm** [comment]
hi, 能再具体一点描述吗

**Comment by Bearx666** [comment]
> hi, 能再具体一点描述吗

我也是有同样的问题，就是我之前向您提问过的，比如开了两个网页，一个是您的网页（比如打开在第10页），另一个是leetcode，然后在leetcode上写完题目后切换回您的网页会重新加载，回到第一页的状态

**Comment by Bearx666** [comment]
> hi, 能再具体一点描述吗

我也是有同样的问题，就是我之前向您提问过的，比如开了两个网页，一个是您的网页（比如打开在第10页），另一个是leetcode，然后在leetcode上写完题目后切换回您的网页会重新加载，回到第一页的状态

**Comment by huxulm** [comment]
> > hi, 能再具体一点描述吗
> 
> 我也是有同样的问题，就是我之前向您提问过的，比如开了两个网页，一个是您的网页（比如打开在第10页），另一个是leetcode，然后在leetcode上写完题目后切换回您的网页会重新加载，回到第一页的状态

谢谢你的反馈！这个问题和最近引入的一个库有关，问题已修复。
