### ISSUE TITLE
[Feature] 在题单中加入进度追踪及显示

### ISSUE THREAD

**Issue by MrAru** [huxulm/lc-rating#30]
### Background

首先感谢各位 Dev 的开发。我近期在照着 0x3f 大佬的题单刷题，发现这个网站非常实用，聚合了全部题单，以及在难度练习中对各档次的题目做了划分，还有进度追踪功能。但我使用中不方便的点在于，我是单纯对照着题单页面 (https://huxulm.github.io/lc-rating/list) 来刷题的，但进度追踪功能只有在难度练习页面 (https://huxulm.github.io/lc-rating/zen) 存在。这导致我每在 list 页面做完一道题，都需要去 zen 页面标记上，远不如能直接在 list 页面直接标记来的方便。此外，list 页面与 zen 页面部分题目互相不重合，而 zen 页面也不能按照题目号进行搜索，即使我现在在 zen 页面标记 AC 的题，也效率较低。最后，一页题单里的题往往需要耗时几天到一两周不等的时间来全部做完，在此期间不能在 list 页面直观看到哪些题还没有做，需要额外的记录来回顾每道题的状态。

### Suggestion

在题单页面也加入每道题的进度展示 和/或 标记进度的功能。或许可以在每道题的链接前方加入一个下拉选项框，从中可以选择并标记每道题的状态。如果无状态则为空。AC / Working 等不同状态可以用不同颜色进行区分。每道题在 list 及 zen 页面的进度状态唯一，在一个页面上对状态进行的改动会反映在另一个页面上。

**Comment by wnykuang** [comment]
非常好的feature，我觉得很有道理，甚至应该把zen 里面的progress 和lc-list 里面的progress 是同步的
